In [2]:
#Task 1 - Load and Inspect the Data
import pandas as pd

In [6]:
df = pd.read_csv('malazan_bridgeburners.csv')

#Display the first 5 rows
df.head()

,Name,Role,Battles_Fought,Avg_Damage,Healing_Spells,Injuries_Sustained
0,Whiskeyjack,Commander,12,82,0,3
1,Quick Ben,Mage,9,91,12,1
2,Fiddler,Sapper,7,78,0,5
3,Kalam Mekhar,Assassin,8,85,0,2
4,Hedge,Sapper,6,80,0,4

In [4]:
#Show column names and data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                10 non-null     str
 1   Role                10 non-null     str
 2   Battles_Fought      10 non-null     int64
 3   Avg_Damage          10 non-null     int64
 4   Healing_Spells      10 non-null     int64
 5   Injuries_Sustained  10 non-null     int64
dtypes: int64(4), str(2)
memory usage: 794.0 bytes

In [8]:
#Print the number of rows and columns
df.shape

(10, 6)

In [9]:
#Task 2 - Summary Statistics
df.describe()

       Battles_Fought  Avg_Damage  Healing_Spells  Injuries_Sustained
count       10.000000   10.000000       10.000000           10.000000
mean         9.500000   83.400000        1.800000            2.700000
std          3.374743    7.662318        3.823901            1.888562
min          4.000000   69.000000        0.000000            0.000000
25%          7.250000   78.500000        0.000000            1.250000
50%          9.500000   83.500000        0.000000            2.500000
75%         11.750000   89.500000        1.500000            3.750000
max         15.000000   94.000000       12.000000            6.000000

In [10]:
#Find the mean of Battles_Fought
df['Battles_Fought'].mean()

np.float64(9.5)

In [13]:
#Find the median of Avg_Damage
df['Avg_Damage'].median()

np.float64(83.5)

In [14]:
#Find the maximum Healing_Spells
df['Healing_Spells'].max()

np.int64(12)

In [24]:
#Task 3 - Filtering and Selection
#Filter to find warriors with Battles_Fought > 7 and Avg_Damage > 85
df[(df['Battles_Fought'] > 7) & (df['Avg_Damage'] > 85)]

,Name,Role,Battles_Fought,Avg_Damage,Healing_Spells,Injuries_Sustained
1,Quick Ben,Mage,9,91,12,1
7,Karsa Orlong,Warrior,15,94,0,6
8,Trull Sengar,Warrior,11,88,0,1
9,Onos T'oolan,Undead Warrior,13,90,0,0

In [28]:
#Create a new DataFrame of these elite fighters and display it
elite_fighters = df[(df['Battles_Fought'] > 7) & (df['Avg_Damage'] > 85)]

elite_fighters

,Name,Role,Battles_Fought,Avg_Damage,Healing_Spells,Injuries_Sustained
1,Quick Ben,Mage,9,91,12,1
7,Karsa Orlong,Warrior,15,94,0,6
8,Trull Sengar,Warrior,11,88,0,1
9,Onos T'oolan,Undead Warrior,13,90,0,0

In [32]:
#Sort the result by Avg_Damage in descending order

elite_fighters.sort_values(by= 'Avg_Damage', ascending=False)

,Name,Role,Battles_Fought,Avg_Damage,Healing_Spells,Injuries_Sustained
7,Karsa Orlong,Warrior,15,94,0,6
1,Quick Ben,Mage,9,91,12,1
9,Onos T'oolan,Undead Warrior,13,90,0,0
8,Trull Sengar,Warrior,11,88,0,1

In [37]:
#Task 4 - Create a Calculated Column
#Add a new column called Battle_Efficiency

df['Battle_Efficiency'] = (df['Avg_Damage'] * df['Battles_Fought']) / (df['Injuries_Sustained'] + 1)

df.head()

,Name,Role,Battles_Fought,Avg_Damage,Healing_Spells,Injuries_Sustained,Battle_Efficiency
0,Whiskeyjack,Commander,12,82,0,3,246.000000
1,Quick Ben,Mage,9,91,12,1,409.500000
2,Fiddler,Sapper,7,78,0,5,91.000000
3,Kalam Mekhar,Assassin,8,85,0,2,226.666667
4,Hedge,Sapper,6,80,0,4,96.000000

In [42]:
#Task 5 - Grouping and Saving Results
#Group data by Role and calculate the average Battle_Efficiency

bridgeburners_summary = df.groupby('Role')['Battle_Efficiency'].mean().round(2)

bridgeburners_summary

Role
Assassin           226.67
Commander          251.33
Mage               409.50
Sapper              93.50
Scout               69.00
Undead Warrior    1170.00
Warrior            342.71
Name: Battle_Efficiency, dtype: float64

In [43]:
#Save the grouped summary to a new file bridgeburners_summary.csv

bridgeburners_summary.to_csv('bridgeburners_summary.csv')